[build]
  base = "originhash"
  command = "npm run build"
  publish = "originhash/dist"

[[redirects]]
  from = "/auth/*"
  to = "https://originhash-backend.onrender.com/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://originhash-backend.onrender.com/api/:splat"
  status = 200
  force = true

# React Router SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
